import { defineContentConfig, defineCollection, z } from '@nuxt/content'

export default defineContentConfig({
  collections: {
    landing: defineCollection({
      type: 'page',
      source: '*/landing.md',
      schema: z.object({
        initials: z.string(),
        my_name: z.string(),
        image: z.string(),
        opening_line: z.string(),
        seo: z.object({
          title: z.string(),
          meta_description: z.string(),
          keywords: z.string().nullable().optional(),
          no_index: z.boolean().default(false),
          no_follow: z.boolean().default(false),
          og_image: z.string().optional(),
        }),
        menu_items: z.array(z.object({
          slug: z.string(),
          status: z.string().default('published'),
          sort: z.number().default(0),
          icon: z.string().nullable().optional(),
          heading: z.string(),
          description: z.string(),
        })),
      }),
    }),

    projects: defineCollection({
      type: 'page',
      source: '*/portfolio/**',
      schema: z.object({
        slug: z.string(),
        status: z.string().default('published'),
        year: z.number(),
        post_image: z.string().optional(),
        project_url: z.string().nullable().optional(),
        source_code_url: z.string().nullable().optional(),
        title: z.string(),
        subtitle: z.string(),
        description: z.string(),
        post_image_caption: z.string().nullable().optional(),
        role: z.string(),
        type: z.string(),
        tags: z.array(z.object({
          id: z.string(),
          value: z.string(),
          icon: z.string().nullable().optional(),
          color: z.string().nullable().optional(),
          sort: z.number().default(0),
          name: z.string(),
          skill_level: z.string().nullable().optional(),
        })),
      }),
    }),

    cv: defineCollection({
      type: 'data',
      source: '*/cv.yaml',
      schema: z.object({
        image: z.string(),
        birthdate: z.string(),
        accumulate_work_experience: z.boolean().default(false),
        work_status_attention: z.boolean().default(false),
        welcome_heading: z.string(),
        work_status: z.string(),
        summary: z.string(),
        skills_summary: z.string(),
        stages_summary: z.string(),
        additional_info: z.string().nullable().optional(),
        educational_stages: z.array(z.object({
          id: z.string(),
          from: z.string(),
          to: z.string().nullable().optional(),
          until_today: z.boolean().default(false),
          date_display: z.string().nullable().optional(),
          final_grade: z.string().nullable().optional(),
          degree: z.string(),
          institution: z.string(),
          location: z.string(),
          final_thesis_title: z.string().nullable().optional(),
          final_thesis_grade: z.string().nullable().optional(),
          additional_info: z.string().nullable().optional(),
        })),
        career_stages: z.array(z.object({
          id: z.string(),
          status: z.string().default('published'),
          sort: z.number().default(0),
          from: z.string(),
          to: z.string().nullable().optional(),
          until_today: z.boolean().default(false),
          date_display: z.string().nullable().optional(),
          use_in_accumulate_work_experience: z.boolean().default(false),
          position: z.string(),
          company: z.string(),
          location: z.string(),
          additional_info: z.string().nullable().optional(),
          employment_level: z.string(),
        })),
        skills: z.array(z.object({
          id: z.string(),
          sort: z.number().default(0),
          subsection: z.string(),
          section: z.object({
            id: z.string(),
            sort: z.number().default(0),
            heading: z.string(),
          }),
          tags: z.array(z.object({
            id: z.string(),
            value: z.string(),
            icon: z.string().nullable().optional(),
            color: z.string().nullable().optional(),
            sort: z.number().default(0),
            name: z.string(),
            skill_level: z.string().nullable().optional(),
          })),
        })),
        publications: z.array(z.object({
          id: z.string(),
          title: z.string(),
          subtitle: z.string().nullable().optional(),
          authors: z.array(z.object({
            prefix: z.string().nullable().optional(),
            first_name: z.string(),
            last_name: z.string(),
          })),
          publisher: z.string().nullable().optional(),
          identifier: z.object({
            type: z.string(),
            value: z.string(),
          }).optional(),
          location: z.string().nullable().optional(),
          year: z.number(),
          conference: z.string().nullable().optional(),
          journal: z.string().nullable().optional(),
          url: z.string().nullable().optional(),
          additional_fields: z.array(z.object({
            name: z.string(),
            value: z.string(),
          })).optional().default([]),
        })),
      }),
    }),

    contact: defineCollection({
      type: 'page',
      source: '*/contact.md',
      schema: z.object({
        show_direct_message: z.boolean().default(true),
        contact_introduction: z.string(),
        direct_message_introduction: z.string(),
        socials: z.array(z.object({
          id: z.string(),
          name: z.string(),
          link: z.string(),
          icon: z.string().nullable().optional(),
          sort: z.number().default(0),
        })),
      }),
    }),

    legalNotice: defineCollection({
      type: 'page',
      source: '*/legal-notice.md',
      schema: z.object({
        full_name: z.string(),
        street_and_number: z.string().nullable().optional(),
        zipcode_and_town: z.string(),
        mail_address: z.string(),
        contact_form_url: z.string(),
        country: z.string(),
        address_info: z.string(),
      }),
    }),
  },
})
