<script setup lang="ts">
const landingStore = useLandingStore()
const projectStore = useProjectStore()
const designStore = useDesignStore()
const cvStore = useCvStore()
const contactStore = useContactStore()
const languageStore = useLanguageStore()
const legalNoticeStore = useLegalNoticeStore()

const language: Ref<string> = ref('')

const { data: landing } = await useAsyncData('landing_page', (): Promise<Landing> => {
  return $fetch('/api/landingPage')
})

const { data: cvData } = await useAsyncData('Curriculum_vitae_new', (): Promise<CV> => {
  return $fetch('/api/cv')
})

const { data: projectPosts } = await useAsyncData('projectPosts', (): Promise<Project[]> => {
  return $fetch('/api/projects')
})

const { data: contact } = await useAsyncData('contact', (): Promise<Contact> => {
  return $fetch('/api/contact')
})
const { data: legalNotice } = await useAsyncData('legalNotice', (): Promise<LegalNotice> => {
  return $fetch('/api/legalNotice')
})

const loading: Ref<boolean> = ref(false)

const isLoading = computed((): boolean => {
  return loading.value ||
    !landingStore.landingData ||
    !contactStore.contactData ||
    !cvStore.cvData ||
    !projectStore.projects ||
    !legalNoticeStore.legalNoticeData
})

const handleLanguageChange = (newLanguage: string): void => {
  languageStore.setLanguage(newLanguage)
}

const handleThemeChange = (newTheme: string): void => {
  console.log('Theme changed to:', newTheme)
}

onBeforeMount((): void => {
  languageStore.initLanguage()
  designStore.initTheme()
  language.value = languageStore.getCurrentLanguage()
})

onMounted((): void => {
  languageStore.initLanguage()
  language.value = languageStore.getCurrentLanguage()

  if (!projectStore.projects) {
    projectStore.setProjectsData(projectPosts.value ?? [])
  }
  if (!cvStore.cvData && cvData.value) {
    cvStore.setData(cvData.value)
  }
  if (!contactStore.contactData && contact.value) {
    contactStore.setData(contact.value)
  }
  if (!landingStore.landingData && landing.value) {
    landingStore.setLandingData(landing.value)
  }
  if (!legalNoticeStore.legalNoticeData && legalNotice.value) {
    legalNoticeStore.setData(legalNotice.value)
  }
})
</script>
<template>
  <Loader v-if="isLoading"></Loader>
  <NuxtErrorBoundary>
    <header class="relative mx-auto max-w-7xl">
      <LangToggle @language-changed="handleLanguageChange" class="" />
      <!-- <ThemeToggle @theme-changed="handleThemeChange" class="" /> -->
    </header>
    <main class="">
      <NuxtLayout>
        <NuxtPage />
      </NuxtLayout>
    </main>
  </NuxtErrorBoundary>
</template>
<style>
.page-enter-active,
.page-enter-leave {
  transition: opacity 0.5s ease;
}

.page-enter-from,
.page-leave-to {
  opacity: 0;
}

.layout-enter-active,
.layout-enter-leave {
  transition: opacity 0.5s ease;
}

.layout-enter-from,
.layout-leave-to {
  opacity: 0;
}

.pulsate-fwd {
  -webkit-animation: pulsate-fwd 15s linear infinite both;
  animation: pulsate-fwd 15s linear infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-4-1 22:54:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-fwd
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }

  50% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }

  50% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>