<script setup>
const landingStore = useLandingStore();
const projectStore = useProjectStore();
const designStore = useDesignStore();
const cvStore = useCvStore();
const contactStore = useContactStore();
const languageStore = useLanguageStore();

const { $directus, $readItems } = useNuxtApp();

const language = ref('');
const { data: landing } = await useAsyncData('landing_page', () => {
  return $fetch('/api/landingPage')
})

const { data: curriculumVitae, refresh: refreshCV } = await useAsyncData('Curriculum_vitae', () => {
  return $directus.request($readItems('Curriculum_vitae', {
    fields: ['*',
      'field.*',
      'translations.*',
      'images.directus_files_id.*',
      'skills.item.*',
      'skills.collection',
      'skills.item.tags.*',
      'skills.item.tech_tags.tech_stack_tags_id.*',
      'skills.item.tech_tags.tech_stack_tags_id.skill_level.*',
      'skills.item.tools_tags.tags_tools_id.*',
      'skills.item.other_tags.tags_id.*',
      'skills.item.languages_tags.tags_languages_id.*',
      'skills.item.tags_soft_skills.tags_soft_skills_id.*',
      'publications.publications_id.*',
      'socials.contact_socials_id.*'
    ]
  }))
})

const { data: cvData } = await useAsyncData('Curriculum_vitae_new', () => {
  return $fetch('/api/cv')
})
console.log(cvData.value);

const { data: projectPosts } = await useAsyncData('projectPosts', () => {
  return $fetch('/api/projects')
})

const { data: contact } = await useAsyncData('contact', () => {
  return $fetch('/api/contact')
})


const loading = ref(false);

const isLoading = computed(() => {
  return loading.value ||
    !landingStore.landingData ||
    !contactStore.contactData ||
    !cvStore.data ||
    !projectStore.projects
})

const handleLanguageChange = (newLanguage) => {
  languageStore.setLanguage(newLanguage);
}

const handleThemeChange = (newTheme) => {
  console.log('Theme changed to:', newTheme);
}

onBeforeMount(() => {
  languageStore.initLanguage();
  designStore.initTheme();
  language.value = languageStore.getCurrentLanguage()
});

onMounted(() => {

  // loading.value = true
  languageStore.initLanguage();
  language.value = languageStore.getCurrentLanguage();
  if (projectStore.projects === null) {
    projectStore.setProjectsData(projectPosts.value);
  }
  if (!cvStore.data) {
    cvStore.setData(curriculumVitae.value);
  }
  if (contactStore.contactData === null) {
    contactStore.setData(contact.value);
  }
  if (landingStore.landingData === null) {
    landingStore.setLandingData(landing.value);
  }
  // loading.value = false
});
</script>
<template>
  <Loader v-if="isLoading"></Loader>
  <NuxtErrorBoundary>
    <header class="relative mx-auto max-w-7xl">
      <LangToggle @language-changed="handleLanguageChange" class="" />
      <!-- <ThemeToggle @theme-changed="handleThemeChange" class="" /> -->
    </header>
    <main class="">
      <NuxtLayout>
        <NuxtPage />
      </NuxtLayout>
    </main>
  </NuxtErrorBoundary>
</template>
<style>
.page-enter-active,
.page-enter-leave {
  transition: opacity 0.5s ease;
}

.page-enter-from,
.page-leave-to {
  opacity: 0;
}

.layout-enter-active,
.layout-enter-leave {
  transition: opacity 0.5s ease;
}

.layout-enter-from,
.layout-leave-to {
  opacity: 0;
}

.pulsate-fwd {
  -webkit-animation: pulsate-fwd 15s linear infinite both;
  animation: pulsate-fwd 15s linear infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-4-1 22:54:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-fwd
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }

  50% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }

  50% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>